import { UserProfile } from './types';

export const DEMO_PROFILE: UserProfile = {
  id: 'user_1',
  username: 'alex',
  name: 'Alex',
  tagline: 'A curious mind, collecting experiences, stories and good vibes.',
  bio: 'Chasing sunsets, discovering indie acoustic tunes, and getting lost in mountains. I believe that outside of work, we are defined by the memories we build and the small things that bring us joy.',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
  coverImageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=2000&q=80',
  handwrittenNoteHeader: 'Same Person, More to Explore',
  handwrittenNoteFooter: 'Collect Moments Not Things',
  quoteBlock: 'Collecting moments, not things.',
  statusPill: '🌿 Exploring • Learning • Growing',
  location: 'Brooklyn, NY',
  socials: {
    instagram: 'https://instagram.com',
    linkedin: 'https://linkedin.com',
    github: 'https://github.com',
    youtube: 'https://youtube.com',
    website: 'https://avero.app/u/alex',
  },
  hobbies: [
    '🏔️ Mountain Trekking',
    '📸 Landscape Photography',
    '🎸 Acoustic Guitar',
    '☕ Specialty Coffee Brewing',
    '📖 Sci-Fi Reading',
    '⛺ Stargazing',
  ],
  personalityTraits: [
    'ENFP (The Campaigner)',
    'Night Owl',
    'Curious Explorer',
    'Empathic Listener',
    'Minimalist',
  ],
  lifestyleBadges: [
    'Early Riser on Treks',
    'Black Coffee Only',
    'Analog Film Enthusiast',
    'Vinyl Record Collector',
  ],
  favoriteQuotes: [
    '"Not all those who wander are lost." — J.R.R. Tolkien',
    '"The journey of a thousand miles begins with a single step."',
    '"Good people, better stories."',
  ],
  likes: [
    'Cold Mountain Air',
    'Lo-Fi Beats at 2 AM',
    'Fresh Espresso',
    'Road Trips with No Map',
    'Old Book Smell',
  ],
  dislikes: [
    'Loud Alarms',
    'Soggy Fries',
    'Small Talk in Elevators',
    'Slow Internet',
  ],
  travel: [
    {
      id: 'tr_1',
      category: 'travel',
      title: 'Kyoto',
      subtitle: 'Arashiyama & Fushimi Inari',
      imageUrl: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=600&q=80',
      description: 'Bamboo groves, serene shrines, and autumn foliage.',
    },
    {
      id: 'tr_2',
      category: 'travel',
      title: 'Iceland',
      subtitle: 'Golden Circle & South Coast',
      imageUrl: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=600&q=80',
      description: 'Glaciers, waterfalls, and dancing northern lights.',
    },
    {
      id: 'tr_3',
      category: 'travel',
      title: 'Amalfi Coast',
      subtitle: 'Positano & Ravello',
      imageUrl: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=600&q=80',
      description: 'Cliffside coastal views and fresh lemon gelato.',
    },
    {
      id: 'tr_4',
      category: 'travel',
      title: 'Swiss Alps',
      subtitle: 'Zermatt & Matterhorn',
      imageUrl: 'https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=600&q=80',
      description: 'Alpine trains, fresh snowfall, and scenic mountain trails.',
    },
  ],
  music: [
    {
      id: 'mu_1',
      category: 'music',
      title: 'Phoebe Bridgers',
      subtitle: 'Punisher / Motion Sickness',
      imageUrl: 'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?auto=format&fit=crop&w=600&q=80',
    },
    {
      id: 'mu_2',
      category: 'music',
      title: 'Arctic Monkeys',
      subtitle: 'AM & Indie Rock',
      imageUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=600&q=80',
    },
    {
      id: 'mu_3',
      category: 'music',
      title: 'Chill Vibes',
      subtitle: 'Lo-Fi Sunset Playlist',
      imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80',
    },
    {
      id: 'mu_4',
      category: 'music',
      title: 'Indie Folk Hits',
      subtitle: 'Bon Iver & Fleet Foxes Classics',
      imageUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=600&q=80',
    },
  ],
  movies: [
    {
      id: 'mv_1',
      category: 'movie',
      title: 'Interstellar',
      subtitle: 'Christopher Nolan • 2014',
      imageUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80',
    },
    {
      id: 'mv_2',
      category: 'movie',
      title: 'Inception',
      subtitle: 'Mind-bending Masterpiece',
      imageUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80',
    },
    {
      id: 'mv_3',
      category: 'movie',
      title: 'The Dark Knight',
      subtitle: 'Heath Ledger Legacy',
      imageUrl: 'https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?auto=format&fit=crop&w=600&q=80',
    },
    {
      id: 'mv_4',
      category: 'movie',
      title: 'Your Name',
      subtitle: 'Makoto Shinkai Anime',
      imageUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=600&q=80',
    },
  ],
  books: [
    {
      id: 'bk_1',
      category: 'book',
      title: 'Atomic Habits',
      subtitle: 'James Clear',
      imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80',
    },
    {
      id: 'bk_2',
      category: 'book',
      title: 'Sapiens',
      subtitle: 'Yuval Noah Harari',
      imageUrl: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80',
    },
    {
      id: 'bk_3',
      category: 'book',
      title: 'The Alchemist',
      subtitle: 'Paulo Coelho',
      imageUrl: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=600&q=80',
    },
  ],
  food: [
    {
      id: 'fd_1',
      category: 'food',
      title: 'Authentic Ramen',
      subtitle: 'Spicy Tonkotsu Broth',
      imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=600&q=80',
    },
    {
      id: 'fd_2',
      category: 'food',
      title: 'Woodfired Pizza',
      subtitle: 'Neapolitan Style Margherita',
      imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=600&q=80',
    },
    {
      id: 'fd_3',
      category: 'food',
      title: 'Matcha Latte',
      subtitle: 'Oat Milk & Honey',
      imageUrl: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&w=600&q=80',
    },
  ],
};

export const DEMO_PROFILES: UserProfile[] = [
  DEMO_PROFILE,
  {
    ...DEMO_PROFILE,
    id: 'user_2',
    username: 'sophia',
    name: 'Sophia Chen',
    tagline: 'Artist, plant parent, and weekend baker.',
    bio: 'Finding beauty in everyday moments. Paint, ceramics, matcha, and cozy reading nooks.',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=800&q=80',
    statusPill: '🎨 Painting • Baking • Reading',
  },
  {
    ...DEMO_PROFILE,
    id: 'user_3',
    username: 'marcus',
    name: 'Marcus Vance',
    tagline: 'Surfer, vinyl head & street foodie.',
    bio: 'Life is better when you catch the early wave and find the best taco truck in town.',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80',
    statusPill: '🏄 Wave Chaser • Vinyl Collector',
  }
];
